meta_title: "Cuppa"
meta_description: "Set a coffee date anonymously with one of your friends, on your time, at a cafe you love!"
meta_image: "metatag.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@cuppapp"
