# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Location.create(name: "Clubkoffie Amsterdam", address: "Krugerplein 2, Amsterdam")
Location.create(name: "Coffee Bru Amsterdam", address: "Beukenplein 14 H, Amsterdam")
Location.create(name: "Boterham Amsterdam", address: "Andreas Bonnstraat 2, Amsterdam")
Location.create(name: "Filter", address: "Valkenburgerstraat 124, Amsterdam")
Location.create(name: "Hartje Oost", address: "Javastraat 23, Amsterdam")
Location.create(name: "De Ruyschkamer", address: "Ruyschstraat 34 , Amsterdam")
Location.create(name: "Rum Baba", address: "Pretoriusstraat 33, Amsterdam")
Location.create(name: "East57", address: "Eerste Ringdijkstraat 2, Amsterdam")
Location.create(name: "Scandinavian Embassy", address: "Sarphatipark 34, Amsterdam")
Location.create(name: "Bakers and Roasters", address: "Eerste Jacob van Campenstraat 54, Amsterdam")
Location.create(name: "Hutspot", address: "Van Woustraat 4, Amsterdam")
Location.create(name: "De Wasserette", address: "Eerste van der Helststraat 27, Amsterdam")
Location.create(name: "Anne & Max", address: "Gerard Douplein 10, Amsterdam")
Location.create(name: "Anne & Max", address: "Amstelveenseweg 196, Amsterdam")
Location.create(name: "The Coffee Virus", address: "Overhoeksplein 2, Amsterdam")
Location.create(name: "Koffie ende Koeck Amsterdam", address: "Haarlemmerweg 175, Amsterdam")
Location.create(name: "Bar Spek", address: "Admiraal de Ruijterweg 1, Amsterdam")
Location.create(name: "Koffie Academie Amsterdam", address: "Overtoom 95, Amsterdam")
Location.create(name: "Trakteren Amsterdam", address: "Jan Pieter Heijestraat 119 A, Amsterdam")
Location.create(name: "White Label Coffee", address: "Jan Evertsenstraat 136, Amsterdam")
Location.create(name: "Berry Amsterdam", address: "Bilderdijkkade 27, Amsterdam")
Location.create(name: "Fietskantine", address: "Overtoom 141, Amsterdam")
Location.create(name: "Caffènation", address: "Theophile de Bockstraat 37, Amsterdam")
Location.create(name: "Coffee Concepts", address: "Jacob Obrechtstraat 5, Amsterdam")
Location.create(name: "Toki Amsterdam", address: "Binnen Dommersstraat 15, Amsterdam")
Location.create(name: "Two for Joy", address: "Frederiksplein 29, Amsterdam")
Location.create(name: "Two for Joy", address: "Haarlemmerdijk 182, Amsterdam")
Location.create(name: "De Laatste Kruimel", address: "Langebrugsteeg 4, Amsterdam")
Location.create(name: "Gartine Amsterdam", address: "Taksteeg 7, Amsterdam")
Location.create(name: "Vinnies", address: "Haarlemmerstraat 46 HS, Amsterdam")
Location.create(name: "Quartier Putain", address: "Oudekerksplein 4, Amsterdam")
Location.create(name: "Marie Stella Maris", address: "Keizersgracht 357, Amsterdam")
# AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

